### PR TITLE
The panther_diagnostics reconfiguration

### PR DESCRIPTION
**Pull request by pawelir**
### Description

Hi gents! The `system_monitor` node is missing proper reconfiguration ability.

- It incorporates `generate_parameter_library`
- Params are defined and respective constraints/descriptions are provided
- However, config file-based node reconfiguration without rebuilding the whole package is impossible.

Implemented changes

- The exact config file added
- Support in launch file

### Requirements

- [X] Code style guidelines followed
- [ ] Documentation updated

### Tests 🧪

- [ ] Robot
- [ ] Container
- [ ] Simulation
- [X] Raw test

Feel free to test changes, I did a quick check on my end 🤙🏼 

## Summary by CodeRabbit

- **New Features**
  - Introduced a new configuration file for system monitoring parameters.
  - Added functionality to specify a configuration file for the system monitor during launch.

- **Changes**
  - Restructured the configuration format for system monitoring.
  - Updated the source of parameters for the system monitor library.
  - Default values for certain parameters have been adjusted to enhance monitoring accuracy.

- **Bug Fixes**
  - Simplified parameter definitions while retaining default values.

### CODE REVIEW

**Comment by KmakD** [comment]
That makes a lot of sense and would require changes in several packages. I will bring that up in tomorrow's planning to see what the approach for that would be, especially since we are introducing a master config directory for easier configuration.
BTW, I absolutely love how you are marked as "First-time contributor" :laughing:

**Comment by pawelir** [comment]
I don't think there are other packages with `generate_parameter_library` based parameters.

Then make sure this PR is merged so I have at least one contribution 😅

**Comment by KmakD** [comment]
There are in `ros2-lynx-devel` branch which is about to be merged into `ros2-devel` so I'm thinking ahead 😜

**Comment by KmakD** [comment]
That's what I thought gonna happen after husarion_ugv merge :anguished: 
We will address this in the future but If you still want to contribute, please feel free to do so. You would ofc need to resolve the conflicts.

One more thing, the parameters file should be placed in `src` directory, as its used only during compilation. This is also approach used by PickNik itself and incorporated for example in Moveit2. The name should be `system_monitor_parameters.yaml`

**Review by KmakD — APPROVED** [review]
LGTM

**Pull request merged**
